# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy (With Functional Tests)

on:
  release:
    types:
      - released
  push:
    tags:
      - 'v*.*.*'
env:
  B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
  B2_BUCKET_ID: ${{ secrets.B2_BUCKET_ID }}

  B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
  B2_APP_KEY_ID: ${{ secrets.B2_APP_KEY_ID }}
  B2_APP_KEY_NAME: ${{ secrets.B2_APP_KEY_NAME }}
  B2_APP_KEY_PREFIX: ${{ secrets.B2_APP_KEY_PREFIX }}

  OLD_B2_APP_KEY: ${{ secrets.OLD_B2_APP_KEY }}
  OLD_B2_APP_KEY_ID: ${{ secrets.OLD_B2_APP_KEY_ID }}
  OLD_B2_APP_KEY_NAME: ${{ secrets.OLD_B2_APP_KEY_NAME }}
  OLD_B2_APP_KEY_PREFIX: ${{ secrets.OLD_B2_APP_KEY_PREFIX }}

jobs:
  test:
    name: 'Install and test package'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.4]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # move .npmrc to not cause  "Maximum call stack size exceeded" error when npm install executes
      - run: |
          npm install
          npm test

  publish-package:
    needs:
      - test
    name: 'Deploy to GH Packages'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.4]

    steps:
      - name: Deploy
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@ks-labs'
      - run: echo "registry=https://npm.pkg.github.com/ks-labs" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
