# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GH Packages

on:
  release:
    types:
      - released
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-package:
    name: 'Deploy Package to GH Packages'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.4]

    needs: [test]
    steps:
      - name: Deploy
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@ks-labs'
      - run: echo "registry=https://npm.pkg.github.com/ks-labs" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
